### ISSUE TITLE
Features tracking issue

### ISSUE THREAD

**Issue by al3mart** [al3mart/para-onboarding#3]
Per the diagram in this repo README, in any specific order:

- [x] Check if the para being onboarded needs a permanent or temporary slot, if any - #1 
- [x] Paras being onboarded that doesn't exist in Rococo need to be registered
- [x] Manager for the para needs some initial funds #13 
- [x] #6
- [x] Remove manager lock from the onboarded para #10
- [x] Para sovereign account needs some initial funds #10
- [x] Integrate with Github issues - maybe Github actions #12 (needs iteration)
- [x] Proper key management
